### ISSUE TITLE
enum .ToString() returns a number and not the actual value name

### ISSUE THREAD

**Issue by TriEdgeAIDeprecated** [Saltarelle/SaltarelleCompiler#384] opened 2015-02-11 05:38 UTC
Example:

```
enum Test
{
    Alfa = 1,
    Beta = 2
}

Test test = Test.Alfa;
Console.WriteLine(test.ToString()); // this will print 1, but it should print Alfa
```

**Comment by erik-kallen** [comment] 2015-02-11 08:16
Do you have an idea of how to implement this?

**Comment by TriEdgeAI** [comment] 2015-02-11 10:42
Look-up table? { "1": "Alfa", "2": "Beta" }

**Comment by erik-kallen** [comment] 2015-02-11 12:03
The problem is that an enum does not have its own type, it is represented by a regular int (or string in case of [NamedValues] enums). So the method ending up being called is ```Number.toString```.

**Comment by geoffreymcgill** [comment] 2016-12-16 07:00
Just to close this issue off for others that might run into this problem, this functionality is supported correctly in [Bridge](http://bridge.net/).

http://deck.net/29c2bc44011dc1942b3d697eeccf342b

```cs
public class Program
{
    public static void Main()
    {
        Test test = Test.Alfa;
        Console.WriteLine(test.ToString());
    }
}

enum Test
{
    Alfa = 1,
    Beta = 2
}
```

Hope this helps.

**Closed by geoffreymcgill** 2016-12-16 07:00 UTC
Labels: enhancement
